### ISSUE TITLE
Test performance of implementation

### ISSUE THREAD

**Issue by brokenpath** [brokenpath/csvreader#6]
Performance of an implementation is a minor concern as long as its faster then fastavro ~1.4mb/s on a decent cpu. if its possible to automate regression performance tests, such that it doesn't degrade that would be awesome. Also visualizing performance through flame graphs would be a good idea to see where time is spent.

**Comment by leanarthropods** [comment]
I added a performance test using pytest-benchmark. It runs through a ~20MB csv file. The type of test data might have to be adjust a bit, as at the moment it doesn't 'complicated' data such as escaped characters or nested quotes.

The timings so far are:

Standard csv module: 1-2s
regexcsv: ~4s
scancsv: ~11s

I tried to play around with scancsv to see if it could be improved, and by inlining everything, minimizing attribute access and other minor improvements,  the best I could get was ~8s. So still quite a bit slower than the other two.
