### ISSUE TITLE
Did a branch -> branch -> master merge but failed. 

### ISSUE THREAD

**Issue by brokenpath** [brokenpath/csvreader#9]
I didnt do a pull when merging, and need to update the performance tests i assume. Also arpeggio needs a initializer, and be added to performance tests. 

i'll fix it tonight when i have the time sorry about that.

**Comment by kun1dude** [comment]
Arpeggio is probally not worth testing. It scales horribly.
I played around with another parser (lark parser), but still really slow and bad memory use (for larger files).

**Comment by brokenpath** [comment]
I guess the question is the scaling factor. But having something super simple that describes a grammar you can take of the internet might not be a bad idea, particularly if it can be used as an "oracle" testing a more optimized version but where correctness isn't the highest priority. (There are also other "almost" csv formats which might be tough to handle with a normal csv parser). But yeah if it sucks up memory thats not so great, cpu can be more easily scaled by running more but if they pop with a 100 mb file its not so great.

**Comment by brokenpath** [comment]
seems like performance tests were included
